### ISSUE TITLE
[BUG] Config not migrated

### ISSUE THREAD

**Issue by makegodhere** [H7KZ/Disenchantment#39]
purpur 1.21.4

```
shatterment:
  enabled: true
  disabled-worlds: []
  enchantments-states:
  - binding_curse:disabled
  - vanishing_curse:disabled
  - curse_of_death:disabled
  - curse_of_drowned:disabled
  - curse_of_mediocrity:disabled
  - curse_of_fragility:disabled
  - curse_of_misfortune:disabled
  - curse_of_breaking:disabled
  anvil:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
    repair:
      reset: false
      cost: true
      base: 10.0
      multiply: 0.25
```

not workig
still can split book with curses

**Comment by alexcrea** [comment]
Hi !
could you download this version https://github.com/alexcrea/Disenchantment/releases/tag/diag-tool
and run `/disenchantment diagnostic`
and send us the diagnostic data

**Comment by H7KZ** [comment]
behaviour confirmed, fixing it

**Comment by H7KZ** [comment]
behaviour not confirmed, made mistake, works as expected

**Comment by makegodhere** [comment]
https://github.com/user-attachments/assets/0cea6d2d-6dc2-465f-b852-f5372bb999e4

**Comment by makegodhere** [comment]
cancel word not working too

```
# DO NOT EDIT THESE VALUES
migration: 4
locales:
- cs
- en
# ----------------------------------------------------------------------------------------
# For descriptions of each option, see the wiki:
# https://github.com/H7KZ/Disenchantment/CONFIG.md
# ----------------------------------------------------------------------------------------

enabled: true

locale: en

event-priorities:
  disenchant-click: HIGHEST
  disenchant: HIGHEST
  shatter-click: HIGHEST
  shatter: HIGHEST

# ----------------------------------------------------------------------------------------

disenchantment:
  enabled: true
  disabled-worlds: []
  disabled-materials: []
  enchantments-states:
  - binding_curse:cancel
  - vanishing_curse:cancel
  - curse_of_death:cancel
  - curse_of_drowned:cancel
  - curse_of_mediocrity:cancel
  - curse_of_fragility:cancel
  - curse_of_misfortune:cancel
  - curse_of_breaking:cancel
  anvil:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
    repair:
      reset: false
      cost: true
      base: 10.0
      multiply: 0.25

# ----------------------------------------------------------------------------------------

shatterment:
  enabled: true
  disabled-worlds: []
  enchantments-states:
  - binding_curse:cancel
  - vanishing_curse:cancel
  - curse_of_death:cancel
  - curse_of_drowned:cancel
  - curse_of_mediocrity:cancel
  - curse_of_fragility:cancel
  - curse_of_misfortune:cancel
  - curse_of_breaking:cancel
  anvil:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
    repair:
      reset: false
      cost: true
      base: 10.0
      multiply: 0.25
```
