### ISSUE TITLE
[BUG] book split not working

### ISSUE THREAD

**Issue by makegodhere** [H7KZ/Disenchantment#42]
![Image](https://github.com/user-attachments/assets/8da3bed9-8ab1-4e4f-87ef-f7e43d1a3a5f)

![Image](https://github.com/user-attachments/assets/2a5a2398-22a6-490f-94cc-a85548669268)

![Image](https://github.com/user-attachments/assets/5638021d-14c4-4079-84f2-90bcb8a78241)

```
# ↓ DO NOT EDIT THESE VALUES ↓
migration: 5
locales:
- cs
- en
# ↑ DO NOT EDIT THESE VALUES ↑
# ----------------------------------------------------------------------------------------
# For descriptions of each option, see the wiki:
# https://github.com/H7KZ/Disenchantment/CONFIG.md
# ----------------------------------------------------------------------------------------

enabled: true

locale: en

event-priorities:
  disenchant-click: HIGHEST
  disenchant: HIGHEST
  shatter-click: HIGHEST
  shatter: HIGHEST

# ----------------------------------------------------------------------------------------

disenchantment:
  enabled: true
  disabled-worlds: []
  disabled-materials: []
  enchantments-states: []
  anvil:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
    repair:
      reset: false
      cost: true
      base: 10.0
      multiply: 0.25

# ----------------------------------------------------------------------------------------

shatterment:
  enabled: true
  disabled-worlds: []
  enchantments-states:
  - binding_curse:disable
  - vanishing_curse:disable
  - curse_of_fragility:disable
  - curse_of_death:disable
  - curse_of_misfortune:disable
  - curse_of_mediocrity:disable
  - curse_of_breaking:disable
  - curse_of_drowned:disable
  anvil:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
    repair:
      reset: false
      cost: true
      base: 10.0
      multiply: 0.25
```

![Image](https://github.com/user-attachments/assets/77f026b3-53e1-418c-8ee1-6deec1f66dad)
